services:
    db:
        image: postgres
        restart: always
        container_name: movie-rental-db
        volumes:
            - db-data:/var/lib/postgresql/data
        env_file:
            - .env
        ports:
            - '5432:5432'
    
    adminer:
        image: adminer:latest
        container_name: movie-rental-adminer
        environment:
            ADMINER_DEFAULT_SERVER: db
        ports:
            - "8080:8080"

volumes:
    db-data: