services:
    app:
        build: .
        container_name: movie-rental
        volumes:
            - .:/usr/src/app
        env_file:
            - .env
        depends_on:
            - db

    db:
        image: postgres
        restart: always
        container_name: movie-rental-db
        volumes:
            - db-data:/var/lib/postgresql/data
        env_file:
            - .env
        ports:
            - '5432:5432'
volumes:
    db-data:
